version: '3.9'

networks:
  postgres:
    driver: bridge

services:
#  web:
#    image: nginx
#    volumes:
#      - ./templates:/etc/nginx/templates
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - '8080:80'
#    environment:
#      - NGINX_HOST=127.0.0.1
#      - NGINX_PORT=80
#    depends_on:
#      - db

  db:
    container_name: postgres_container
    image: postgres:14.8
    ports:
      - '5431:5432'
    volumes:
      - ./db_psql:/var/lib/postgresql/newdata
    environment:
      POSTGRES_DB: 'diplom'
      POSTGRES_USER: 'user_admin'
      POSTGRES_PASSWORD: 'Diplom2023'
      PGDATA: /var/lib/postgresql/newdata
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bakhmudov01@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "Gjhn1002"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
