# Generated by Django 4.2.1 on 2023-05-26 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('age', models.CharField(max_length=3)),
                ('image', models.ImageField(upload_to='')),
                ('pushkin', models.BooleanField(default=False)),
                ('children', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=None)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_time', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
                ('occupied', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.showtime')),
            ],
            options={
                'unique_together': {('row', 'number')},
            },
        ),
    ]
