# Generated by Django 4.2.1 on 2023-05-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_total_price_ticket_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
