# Generated by Django 4.2.1 on 2023-05-30 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_showtime_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesettings',
            old_name='model',
            new_name='movie',
        ),
    ]
