# Generated by Django 4.2.1 on 2023-05-30 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_seat_movie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('movie', 'showtime', 'row', 'number')},
        ),
    ]
